name: ui_e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  curved_navigation_bar: ^1.0.6
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  cupertino_icons: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
